language: rust
cache: cargo
before_script: (cargo update && (cargo install rustfmt || true))
rust:
  - stable
  - beta
  - nightly
  - 1.9.0
  - 1.8.0
  - 1.7.0
matrix:
  allow_failures:
    - rust: nightly
script:
- |
  cargo fmt -- --write-mode=diff &&
  cargo build &&
  cargo test
