language: rust
cache: cargo
before_script:
- cargo update || true
- cargo install rustfmt || true
rust:
  - stable
  - beta
  - nightly
  - 1.11.0
  - 1.10.0
  - 1.9.0
matrix:
  allow_failures:
    - rust: nightly
script:
- |
  PATH=${HOME}/.cargo/bin:$PATH cargo fmt -- --write-mode=diff &&
  cargo build &&
  cargo test
