language: rust
cache: cargo
before_script:
- cargo update || true
rust:
  - stable
  - beta
  - nightly
  - 1.14.0
  - 1.13.0
  - 1.26.2
matrix:
  include:
   - rust: nightly
     env: TASK=rustfmt
     before_script:
      - rustup component add rustfmt-preview
     script:
      - cargo fmt -- --check
  allow_failures:
    - rust: nightly
      env:
