[package]
name = "pdf"
version = "0.2.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>",
	   "Rasmus Kaj <rasmus@krats.se>"]
license = "MIT"
description = "Generating PDF files in pure Rust."
documentation = "http://rasmus.krats.se/doc/pdf/0.2.0/pdf/"
repository = "https://github.com/kaj/rust-pdf"
readme = "README.md"

build = "src/build_metrics.rs"

[build-dependencies]
lazy_static = "*"

[dependencies]
lazy_static = "*"
time = "*"
